name: TwitterAPI
main: fr.galaxyoyo.spigot.twitterapi.TwitterAPI
version: 1.1.2
author: galaxyoyo

commands:
  tweet:
    permission: twitterapi.commands.tweet
  dm:
    permission: twitterapi.commands.dm

permissions:
  twitterapi.commands.tweet:
    default: op
  twitterapi.commands.dm:
    default: op
